version: 2.1

commands:

  pip_install:
    description: "Install dependencies via pip"
    parameters:
      args:
        type: string
        default: ""
    steps:
      - run:
          name: "Install dependencies via pip"
          command: ./scripts/install_via_pip.sh << parameters.args >>

  conda_install:
    description: "Install dependencies via conda"
    parameters:
      args:
        type: string
        default: ""
    steps:
      - run:
          name: "Install dependencies via conda"
          command: ./scripts/install_via_conda.sh << parameters.args >>

  lint_flake8:
    description: "Lint with flake8"
    steps:
      - run:
          name: "Lint with flake8"
          command: flake8

  lint_black:
    description: "Lint with black"
    steps:
      - run:
          name: "Lint with black"
          command: black --check --diff .

  unit_tests:
    description: "Run unit tests"
    steps:
      - run:
          name: "Run unit tests"
          command: pytest -ra --cov=. --cov-report term-missing

  sphinx:
    description: "Run sphinx"
    steps:
      - run:
          name: "Run sphinx"
          command: sphinx-build -T --keep-going sphinx/source sphinx/build

  configure_github_bot:
    description: "Configure Docusaurus GitHub bot"
    steps:
      - run:
          name: "Configure Docusaurus GitHub bot"
          # Do not do this if we don't have the right org (pytorch), or if this is just a PR
          command: |
            if [[ $CIRCLE_PROJECT_USERNAME == "pytorch" && -z $CI_PULL_REQUEST && -z $CIRCLE_PR_USERNAME ]]; then
              git config --global user.email "docusaurus-bot@users.noreply.github.com"
              git config --global user.name "Captum website deployment script"
              echo "machine github.com login docusaurus-bot password $GITHUB_TOKEN" > ~/.netrc
            fi

  deploy_site:
    description: "Deploy website to GitHub Pages"
    steps:
      - run:
          name: "Deploy website to GitHub Pages"
            # TODO: make the installation above conditional on there being relevant changes (no need to install if there are none)
          command: |
            if ! git diff-tree --no-commit-id --name-only -r HEAD | grep -E "(^docs\/.*)|(^website\/.*)|(^scripts\/.*)|(^sphinx\/.*)|(^tutorials\/.*)"; then
              echo "Skipping deploy. No relevant website files have changed"
            elif [[ $CIRCLE_PROJECT_USERNAME == "pytorch" && -z $CI_PULL_REQUEST && -z $CIRCLE_PR_USERNAME ]]; then
              mkdir -p website/static/.circleci && cp -a .circleci/. website/static/.circleci/.
              ./scripts/build_docs.sh -b
              cd website
              GIT_USER=docusaurus-bot USE_SSH=false yarn run publish-gh-pages
            else
              echo "Skipping deploy."
            fi


jobs:

  lint_test_py36_pip:
    docker:
      - image: circleci/python:3.6.8
    steps:
      - checkout
      - pip_install:
          args: "-n -f"
      - lint_flake8
      - lint_black
      - unit_tests
      - sphinx

  lint_test_py36_pip_release:
    docker:
      - image: circleci/python:3.6.8
    steps:
      - checkout
      - pip_install:
          args: "-f"
      - lint_flake8
      - lint_black
      - unit_tests
      - sphinx

  lint_test_py37_conda:
    docker:
      - image: continuumio/miniconda3
    steps:
      - checkout
      - conda_install:
          args: "-n"
      - lint_flake8
      - lint_black
      - unit_tests
      - sphinx

  test_cuda_multi_gpu:
    machine:
      image: circleci/classic:latest
    resource_class: gpu.medium
    steps:
      - checkout
      - run: 'sudo apt-get install python3.7'
      - run: 'sudo python3.7 -m pip install pip'
      - run: 'python3.7 -m pip install -e .[dev]'
      - unit_tests

aliases:

  - &exclude_ghpages_fbconfig
    branches:
      ignore:
        - gh-pages
        - fb-config


workflows:

  lint_and_test:
    jobs:
      - lint_test_py36_pip:
          filters: *exclude_ghpages_fbconfig
      - lint_test_py36_pip_release:
          filters: *exclude_ghpages_fbconfig
      - lint_test_py37_conda:
          filters: *exclude_ghpages_fbconfig
      - test_cuda_multi_gpu:
          filters: *exclude_ghpages_fbconfig
